_format_version: "3.0"

services:
- name: auth-service
  url: http://auth-service:9898
  routes: 
  - name: sign-up
    paths:
      - /auth/v1/signup
    strip_path: false

- name: user-service
  url: http://user-service:9810
  routes:
  - name: get-user
    paths:
      - /user/v1/getUser
    strip_path: false
    preserve_host: false

  - name: health
    paths:
      - /health
    strip_path: false
    preserve_host: false
