version: '3.8'


services:
  # Controller node
  kafka-controller:
    image: confluentinc/cp-kafka:7.4.4
    hostname: kafka-controller
    container_name: kafka-controller
    ports: 
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU3OEVBNkY1Njc1NTM3Qg
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-controller:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

  # Broker Node
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - "9092:9092"
    depends_on:
      - kafka-controller
    environment:
      KAFKA_NODE_ID: 2
      CLUSTER_ID: MkU3OEVBNkY1Njc1NTM3Qg
      KAFKA_PROCESS_ROLES: broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-controller:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.112:9092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  # MySQL DB
  mysql:
    image: mysql:8.3.0
    container_name: mysql-8
    environment:
      MYSQL_USER: test
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # auth service
  auth-service:
    image: auth-service
    container_name: auth-service
    ports: 
      - "9898:9898"
    depends_on:
      - kafka
      - mysql

  # user service
  user-service:
    image: user-service
    container_name: user-service
    ports:
      - "9810:9810"
    depends_on:
      - kafka
      - mysql

volumes:
  mysql-data:
    driver: local
